### ISSUE TITLE
I have questions about the bot

### ISSUE THREAD

**Issue by MarksMK** [MainSilent/Discord-Screenshare#38]
So as i saw in the help command it say run *p (yt link) and the bot will stream the video without downloading , but what is actually happening the bot take so much time as long as the video length 

Ans the second question is it possible to stream from other websites like a movie

**Comment by MainSilent** [comment]
I believe the help message has been misunderstood, The last separated part is only for a direct video link, But it should be possible to use a library like `ytdl-core` to get the raw video link from a youtube video and stream it without downloading.

The second question has more aspects to answer since the bot is just an automated headless website.

![image](https://user-images.githubusercontent.com/70273681/167235335-6da740db-1bc2-487e-8d12-3dc68bd28463.png)

**Comment by K14it5mCFQZLF7BUVKF5QycA04yUjeak** [comment]
so would you like to do stream the video directly instead of downloading a video which will take so long to download & play ?
i wish i have enough experience to do that by my self

**Comment by MainSilent** [comment]
I'm not sure if that approach work but I will check it later, Currently I'm on a deadline for another project.
Please keep this issue open for now.

**Comment by AhmedMondo** [comment]
I have an Idea for a new code 

Its Bot Adder 
Example: 

I gave the program bot invite link 
It will add it to specify guild which i choose it by id and it will automatically add it into that guild

Thx.

I didnt find any other ways to contact you :)

**Comment by MainSilent** [comment]
The update is on my watch list but due to other high priority projects, It will take more time.

**Comment by MainSilent** [comment]
7f2c38a
